set -g prefix C-SPACE
set -g status-position top
set -g base-index 1
set -g renumber-windows on
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g status-right ""
set -g status-left "#S"
set -g mode-keys vi

bind r source-file ~/.config/tmux/tmux.conf 
bind E show-environment -g

bind -T copy-mode-vi / command-prompt -i -p "search down"  "send -X search-forward-incremental \"%%%\""
bind -T copy-mode-vi ? command-prompt -i -p "search up"    "send -X search-backward-incremental \"%%%\""

